version: "3.8"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/rinha
    depends_on:
      - db

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
        
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "max_connections=500"]